#!/usr/bin/env python3
"""Regenerates js/widget/src/generated/metric_names.generated.ts from
metrics/metric_builder.py's VALID_METRICS set (see ADR-0007).

Run this (via `make export-metric-schema`) whenever a metric is added,
renamed, or removed. `tests/metrics/js_export_test.py` fails CI if the
checked-in generated file drifts from VALID_METRICS.
"""

import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from retentioneering.metrics.metric_builder import VALID_METRICS  # noqa: E402

OUTPUT_PATH = (
    REPO_ROOT / "js" / "widget" / "src" / "generated" / "metric_names.generated.ts"
)


def render(metric_names: list[str]) -> str:
    names = ", ".join(f'"{name}"' for name in metric_names)
    return (
        "// AUTO-GENERATED by scripts/export_metric_schema.py from\n"
        "// metrics/metric_builder.py's VALID_METRICS — do not edit by hand.\n"
        "// Regenerate with `make export-metric-schema` after changing VALID_METRICS.\n"
        "\n"
        f"export const METRIC_NAMES = [{names}];\n"
    )


def main() -> None:
    metric_names = sorted(VALID_METRICS)
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(metric_names))
    print(f"Wrote {len(metric_names)} metric names to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
